### ISSUE TITLE
Autoclose when is used to program with clangd

### ISSUE THREAD

**Issue by DuilioPerez** [7HR4IZ3/acode-language-client#1]
Hello! I'm a C/C++ programmer. I've used Vim in Termux to program in C/C++ and I have a plugin installed to use autocompletion and error detection. Many time after, I used Acode to write my code. Since a few time ago, I've see your plugin in Acode Plugins. So I installed. I've see it works fine, but after a few seconds autocompletion stops and few seconds after that, error checking fails too. I'm not used to web programming languages, so I don't know how to fix this.

**Comment by DuilioPerez** [comment]
Hello again! I've made a screen recorder of what happens

https://github.com/7HR4IZ3/acode-language-client/assets/135564120/80684510-43d3-4a74-800e-e1c35d223409

As you can see, I have installed the two plugins, the language client and the C/C++ client. And I have clangd. And yes, I'll give a try to your plugin about vim keybindings. Thanks for reading, and I hope you'll fix this bug

**Comment by 7HR4IZ3** [comment]
Hello, I think I know what the problem is..

So essentially, Acode Language Client uses nodejs sockets to communicate with the server running in termux, which in turn forwards all messages, from the language server process to the socket and from the socket to the language server process.

Problem is when working with the process stdout, sometimes a language server might send the response for a request immediately after the response of another request so what is sent to the socket looks something like this '{...}{...}' the first object being a previous response followed immediately after with another response, hence when it gets to Acode Language Client, which is expecting a json object, it crashes and throws an error.

I'll recommend you install Acode SDK Plugin which adds a console to Acode so you'll know when such errors occur..

This happens randomly, hence it working sometimes and not working other times.

I'm still trying to fix this though, I'll update the server and notify you when ready..

By the way, for cases when you have started the server, opened acode, and opened a file, but nothing still works, closing and reopening that file should work.

**Comment by DuilioPerez** [comment]
I've used Acode SDK plugin and I've found the next warning:

Error {name: "MaxListenersExceededWarning", emitter: r, type: "2-/sdcard/Programming/Cpp/test.c", count: 51}
count: 51
emitter: Object
name: "MaxListenersExceededWarning"
type: "2-/sdcard/Programming/Cpp/test.c"
message: "Possible EventEmitter memory leak detected. 51 2-/sdcard/Programming/Cpp/test.c listeners added. Use emitter.setMaxListeners() to increase limit"
stack: "MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 51 2-/sdcard/Programming/Cpp/test.c listeners added. Use emitter.setMaxListeners() to increase limit↵ at h (https://localhost/__cdvfile_files-external__/plugins/acode.language.client/277.js:2:1867)↵ at c.addListener (https://localhost/__cdvfile_files-external__/plugins/acode.language.client/277.js:2:4429)↵ at r.postMessage (https://localhost/__cdvfile_files-external__/plugins/acode.language.client/355.js:1:24287)↵ at r.doComplete (https://localhost/__cdvfile_files-external__/plugins/acode.language.client/355.js:1:23244)↵ at g.doComplete (https://localhost/__cdvfile_files-external__/plugins/acode.language.client/355.js:1:18018)↵ at https://localhost/__cdvfile_files-external__/plugins/acode.language.client/355.js:1:18320↵ at p.$sendDeltaQueue (https://localhost/__cdvfile_files-external__/plugins/acode.language.client/355.js:1:20453)↵ at Object.getCompletions (https://localhost/__cdvfile_files-external__/plugins/acode.language.client/355.js:1:18293)↵ at https://localhost/js/ace/ext-language_tools.js:1:48108↵ at Array.forEach (<anonymous>)"
get stack: ƒ ()
set stack: ƒ ()
[[Prototype]]: Object
And the next error:
Connection is disposed.
at he (https://localhost/__cdvfile_files-external__/plugins/acode.language.client/main.js:2:268132)
at Object.sendRequest (https://localhost/__cdvfile_files-external__/plugins/acode.language.client/main.js:2:270197)
at d.findDocumentHighlights (https://localhost/__cdvfile_files-external__/plugins/acode.language.client/main.js:2:342736)
at https://localhost/__cdvfile_files-external__/plugins/acode.language.client/798.js:1:3048
at Array.map (<anonymous>)
at EventTarget.<anonymous> (https://localhost/__cdvfile_files-external__/plugins/acode.language.client/798.js:1:3032)
at Object.postMessage (https://localhost/__cdvfile_files-external__/plugins/acode.language.client/main.js:2:427365)
at r.postMessage (https://localhost/__cdvfile_files-external__/plugins/acode.language.client/355.js:1:24308)
at r.findDocumentHighlights (https://localhost/__cdvfile_files-external__/plugins/acode.language.client/355.js:1:24057)
at https://localhost/__cdvfile_files-external__/plugins/acode.language.client/355.js:1:15148

**Comment by DuilioPerez** [comment]
As I've said, I'm not used to web languages, so I don't know what does it means.

**Comment by DuilioPerez** [comment]
Termux shows this:
node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

Node.js v20.11.1

**Comment by 7HR4IZ3** [comment]
Hello, Sorry it took a long time, this issue has been fixed just update the plugin and the server.

**Comment by 7HR4IZ3** [comment]
Did you also update the plugin??

**Comment by DuilioPerez** [comment]
Yes, it's up to date
